### ISSUE TITLE
Issue on Note 8 Oreo

### ISSUE THREAD

**Issue by markcadag** [himangipatel/ImagePickerUtil#8]
`-26 13:04:35.693 13932-13932/ph.beepbeep.beepbeepapp W/System.err: java.io.IOException: No such file or directory
        at java.io.UnixFileSystem.createFileExclusively0(Native Method)
06-26 13:04:35.694 13932-13932/ph.beepbeep.beepbeepapp W/System.err:     at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:281)
        at java.io.File.createTempFile(File.java:2001)
        at com.imagepicker.AppUtils.createImageFile(AppUtils.java:31)
        at com.imagepicker.FilePickUtils.selectImageFromCamera(FilePickUtils.java:137)
        at com.imagepicker.FilePickUtils.onRequestPermissionsResult(FilePickUtils.java:260)
        at ph.beepbeep.beepbeepapp.ui.custom.imagepicker.ImagePickerActivity.onRequestPermissionsResult(ImagePickerActivity.kt:48)
        at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7728)
        at android.app.Activity.dispatchActivityResult(Activity.java:7551)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4487)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4534)
        at android.app.ActivityThread.-wrap20(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1752)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6940)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)`

Gallery and Camera is not showing up, 

Thanks

**Comment by markcadag** [comment]
It's a permission issue, solved this by using a permission library
